# Generated by Django 5.0 on 2024-04-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_articleuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleUser',
        ),
    ]
