# Generated by Django 5.0 on 2024-03-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_author_article_content_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.JSONField(default=None),
        ),
    ]
