# Generated by Django 5.0 on 2024-03-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='visible',
            new_name='published',
        ),
    ]
